"""
HawkEye Report Generator (Module 9 canonical name)
PDF and CSV generation logic lives in reports.py (kept under its
original name so existing imports in app.py keep working); this module
re-exports those and adds the standalone HTML report builder, so both
PDF and HTML report formats are available as the module requires.
"""

import html as html_escape

from reports import build_pdf_report, build_csv_report  # re-exported for the standard module name

__all__ = ["build_pdf_report", "build_csv_report", "build_html_report"]


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>HawkEye Security Report - {filename}</title>
<style>
  body {{ font-family: 'Segoe UI', Tahoma, sans-serif; background:#0f172a; color:#e2e8f0; margin:0; padding:30px; }}
  .container {{ max-width: 960px; margin: auto; }}
  h1 {{ color:#38bdf8; }}
  h2 {{ color:#38bdf8; border-bottom:1px solid #334155; padding-bottom:6px; margin-top:32px; }}
  table {{ width:100%; border-collapse:collapse; margin-top:12px; }}
  th {{ background:#2563eb; color:#fff; padding:10px; text-align:left; font-size:14px; }}
  td {{ background:#1e293b; padding:10px; border-bottom:1px solid #334155; font-size:13.5px; }}
  .badge {{ padding:3px 10px; border-radius:8px; font-weight:700; font-size:12px; }}
  .Critical {{ background:#dc2626; color:#fff; }}
  .High {{ color:#ef4444; font-weight:700; }}
  .Medium {{ color:#facc15; font-weight:700; }}
  .Low {{ color:#22c55e; font-weight:700; }}
  .summary-grid {{ display:flex; gap:16px; flex-wrap:wrap; margin-top:16px; }}
  .summary-card {{ background:#1e293b; border-radius:12px; padding:18px 24px; flex:1; min-width:160px; }}
  .summary-card .num {{ font-size:32px; font-weight:700; color:#38bdf8; }}
  .footer {{ text-align:center; color:#94a3b8; margin-top:40px; font-size:13px; }}
</style>
</head>
<body>
<div class="container">
  <h1>🦅 HawkEye Security Analysis Report</h1>
  <p>File: <strong>{filename}</strong> &nbsp;|&nbsp; Analyzed: {analysis_time}</p>

  <div class="summary-grid">
    <div class="summary-card"><div class="num">{threat_score}</div>Threat Score / 100</div>
    <div class="summary-card"><div class="num">{alert_count}</div>Alerts Detected</div>
    <div class="summary-card"><div class="num">{incident_count}</div>Correlated Incidents</div>
    <div class="summary-card"><div class="num">{failed}</div>Failed Logins</div>
  </div>

  <h2>Executive Summary</h2>
  <p>{insight}</p>

  <h2>Detected Security Alerts</h2>
  <table>
    <tr><th>Severity</th><th>Rule</th><th>MITRE</th><th>Confidence</th><th>Risk</th><th>Evidence</th></tr>
    {alert_rows}
  </table>

  <h2>Correlated Incidents</h2>
  <table>
    <tr><th>Severity</th><th>Correlated By</th><th>Attack Chain</th><th>Risk</th></tr>
    {incident_rows}
  </table>

  <h2>Indicators of Compromise</h2>
  <table>
    <tr><th>Type</th><th>Value</th><th>Attempts</th><th>Failed</th></tr>
    {ioc_rows}
  </table>

  <h2>Recommendations</h2>
  <ul>{recommendation_items}</ul>

  <div class="footer">Generated by HawkEye Security Solutions | {analysis_time}</div>
</div>
</body>
</html>
"""


def _e(value):
    return html_escape.escape(str(value)) if value is not None else ""


def build_html_report(data):
    """Return a standalone HTML report string for the given analysis result."""
    alert_rows = "".join(
        f"<tr><td><span class='badge {a.get('severity','')}'>{_e(a.get('severity'))}</span></td>"
        f"<td>{_e(a.get('rule'))}</td>"
        f"<td>{_e((a.get('mitre') or {}).get('technique_id', 'N/A'))}</td>"
        f"<td>{_e(a.get('confidence', 0))}%</td>"
        f"<td>{_e(a.get('risk_score', 0))}</td>"
        f"<td>{_e((a.get('evidence') or [''])[0])}</td></tr>"
        for a in (data.get("alerts") or [])
    ) or "<tr><td colspan='6'>No alerts detected.</td></tr>"

    incident_rows = "".join(
        f"<tr><td><span class='badge {i.get('severity','')}'>{_e(i.get('severity'))}</span></td>"
        f"<td>{_e(i.get('correlated_by'))}: {_e(i.get('correlated_value'))}</td>"
        f"<td>{_e(i.get('rule_chain'))}</td>"
        f"<td>{_e(i.get('risk_score', 0))}</td></tr>"
        for i in (data.get("incidents") or [])
    ) or "<tr><td colspan='4'>No correlated incidents.</td></tr>"

    ioc_rows = "".join(
        f"<tr><td>{_e(row.get('type'))}</td><td>{_e(row.get('value'))}</td>"
        f"<td>{_e(row.get('attempts'))}</td><td>{_e(row.get('failed_attempts', 0))}</td></tr>"
        for row in (data.get("ioc_flat") or [])
    ) or "<tr><td colspan='4'>No IOCs extracted.</td></tr>"

    recommendation_items = "".join(
        f"<li>{_e(c)}</li>" for c in (data.get("recommended_controls") or [])
    ) or "<li>No specific recommendations — no high-risk alerts detected.</li>"

    html_out = HTML_TEMPLATE.format(
        filename=_e(data.get("filename", "N/A")),
        analysis_time=_e(data.get("analysis_time", "N/A")),
        threat_score=_e(data.get("threat_score", 0)),
        alert_count=_e(data.get("alert_count", 0)),
        incident_count=_e(data.get("incident_count", 0)),
        failed=_e(data.get("failed", 0)),
        insight=_e(data.get("insight", "")),
        alert_rows=alert_rows,
        incident_rows=incident_rows,
        ioc_rows=ioc_rows,
        recommendation_items=recommendation_items,
    )
    return html_out
